version: '3.8'
services:
  web:
    build: .
    container_name: schema-bloc
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./saves:/app/saves
    restart: unless-stopped
